name: Sync to Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Add personal fork as a remote
        run: git remote add fork https://github.com/Lamyzm/front-end.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main

      - name: Push changes to fork
        run: git push fork main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GHCR_TOKEN_FRONT }}
