name: Sync to Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Add upstream repository
        run: git remote add upstream https://github.comeducation-project-knowing/front-end.git

      - name: Add personal fork as a remote
        run: git remote add fork https://github.com/Lamyzm/front-end.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge changes
        run: |
          git checkout main
          git merge upstream/main || (git status && exit 1)

      - name: Push changes to fork
        run: |
          git push https://${{ secrets.GHCR_TOKEN_FRONT }}@github.com/Lamyzm/front-end.git main
